name: my_app
description: "A new Flutter project with multi-utilities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  provider: ^6.1.2
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  http: ^1.4.0
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  intl: ^0.20.2
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  math_expressions: ^3.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  android_home_widget: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
    android: true
    ios: true
    adaptive_icon_foreground: "assets/icon_foreground.png"
    adaptive_icon_background: "#121212" 
    image_path: "assets/icon.png" 
    min_sdk_android: 21
